fix classpath that caused for: Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.ClassVisitor.visit(ILjava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V 	at net.sf.cglib.core.ClassEmitter.begin_class(ClassEmitter.java:101)
git-svn-id: svn://pc-lab14/SVN/xap/trunk/openspaces@135926 eb64e737-3616-4df0-8941-5ee2ae88103d